import "~/styles/globals.css";
import { inter } from "~/app/fonts";

import { GoogleAnalytics } from "@next/third-parties/google";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { NavBar } from "./_components/NavBar";
import { Footer } from "./_components/footer";
import { Toaster } from "~/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProvider>
      <html
        lang="en"
        className={`${GeistSans.variable}`}
        suppressHydrationWarning
      >
        <body className={`${inter.className} antialiased`}>
          <NextTopLoader />
          <ThemeProvider
            attribute="class"
            // defaultTheme="system"
            // enableSystem
            disableTransitionOnChange
          >
            <div className="grid min-h-screen grid-rows-[auto,1fr]">
              <NavBar />
              {children}
              <Toaster />
              <Footer />
            </div>
          </ThemeProvider>
        </body>
        {/* <GoogleAnalytics gaId="G-BNX08YMCR9" /> */}
      </html>
    </SessionProvider>
  );
}
